### ISSUE TITLE
[Bug] TGIS container fails to run on a FIPS cluster

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/caikit-tgis-serving#130]
When deploying a LLM model using the new Caikit+TGIS architecture introduced with #107 , the TGIS container (i.e., transformer-container) fails to start if the cluster has FIPS cryptography enabled.

These are the 2 errors I got in the container logs
`
There was a problem when trying to write in your cache folder (/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
fips.c(145): OpenSSL internal error, assertion failed: FATAL FIPS SELFTEST FAILURE
`
Note: the TRANSFORMERS_CACHE is actually set in the ServinRuntime

This was found on a OpenShift 4.13.18 cluster with RHODS 2.1.2 (aka 1.32.2) and KServe 0.11 installed

**Comment by heyselbi** [comment]
What needs to be done (more like notes to self):
- Create a FIPS enabled cluster
- Check each python library for FIPS as shown [here](https://access.redhat.com/solutions/7035895)

**Comment by bmcfeeters** [comment]
As another data point, I have hit this issue with FIPS enabled OpenShift 4.13.12 cluster and Red Hat OpenShift Data Science operator 2.5.0

It appears it is the tokenizer Python module that is causing the crash.  From a debug container I see the same issue as noted [here ](https://github.com/huggingface/tokenizers/issues/1113) from huggingface.

Unfortunately, I have to redeploy my entire cluster now to make progress since [FIPS cannot be disabled](https://access.redhat.com/solutions/5594191) after OpenShift is fully deployed and running.

**Comment by bdattoma** [comment]
> As another data point, I have hit this issue with FIPS enabled OpenShift 4.13.12 cluster and Red Hat OpenShift Data Science operator 2.5.0
> 
> It appears it is the tokenizer Python module that is causing the crash. From a debug container I see the same issue as noted [here ](https://github.com/huggingface/tokenizers/issues/1113) from huggingface.
> 
> Unfortunately, I have to redeploy my entire cluster now to make progress since [FIPS cannot be disabled](https://access.redhat.com/solutions/5594191) after OpenShift is fully deployed and running.

@bmcfeeters thanks for sharing your case. This issue should be solved on the latest image versions of the runtime which is going to be shipped with operator 2.6.0

**Comment by dtrifiro** [comment]
Fixed in #171, due to [this change](https://github.com/opendatahub-io/caikit-tgis-serving/pull/171/commits/98e8ccf6bb25d12d912d1ebca5e155ad4a741bbf#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R25), this was due to the way the virtualenv was being prepared in the `Dockerfile`
